"""Deterministic Arabic/English cue vocabularies for Stage 3 heuristics.

Deliberately small and maintainable: general discourse/structural signals with
common Egyptian, Gulf/Saudi, Levantine, MSA/Fusha, and English surface variants.
Matching runs against the analysis-only normalized view, so orthographic
variants (diacritics, tatweel, alif/ya forms) match without altering stored text.
This is not a dialect classifier, and source dialect is never treated as a target
audience.
"""

from __future__ import annotations

from app.core.enums import ContentType, HookType

CONTENT_CUES: dict[ContentType, tuple[str, ...]] = {
    ContentType.EDUCATIONAL: (
        "الفرق بين",
        "معنى",
        "شرح",
        "درس",
        "تعلم",
        "طريقة عمل",
        "المفهوم",
        "how to",
        "learn",
        "meaning",
        "explain",
        "the difference",
    ),
    ContentType.CONTROVERSIAL_OPINION: (
        "رايي",
        "بصراحة",
        "الصراحة",
        "اعتقد",
        "الحقيقة",
        "غلط",
        "صح",
        "جدل",
        "in my opinion",
        "honestly",
        "i believe",
        "controversial",
        "i think",
        "wrong",
    ),
    ContentType.FUNNY: (
        "ههه",
        "هههه",
        "مضحك",
        "نكتة",
        "بضحك",
        "funny",
        "lol",
        "hilarious",
        "joke",
    ),
    ContentType.STORY: (
        "مرة",
        "كان في",
        "قصة",
        "حكاية",
        "احكي",
        "حصل",
        "صار",
        "لما",
        "story",
        "once",
        "happened",
        "remember when",
    ),
    ContentType.SURPRISING_FACT: (
        "معلومة",
        "اول مرة",
        "عمرك",
        "غريب",
        "عجيب",
        "مفاجأة",
        "فاجأني",
        "مش متوقع",
        "fact",
        "surprisingly",
        "surprising",
        "actually",
        "amazing",
        "unbelievable",
        "no way",
    ),
    ContentType.EMOTIONAL: (
        "حزين",
        "دموع",
        "بحب",
        "خايف",
        "زعلان",
        "قلبي",
        "فرحان",
        "متحمس",
        "emotional",
        "sad",
        "cried",
        "love",
        "heartbroken",
        "excited",
    ),
    ContentType.NEWS_CURRENT_EVENT: (
        "النهاردة",
        "خبر",
        "اعلن",
        "اليوم",
        "عاجل",
        "الان",
        "news",
        "breaking",
        "announced",
        "today",
    ),
    ContentType.INTERVIEW_INSIGHT: (
        "سؤال",
        "اجابة",
        "قال لي",
        "سألني",
        "interview",
        "asked",
        "explained to me",
    ),
    ContentType.DEBATE: (
        "خلاف",
        "نقاش",
        "ضد",
        "اعترض",
        "debate",
        "argument",
        "disagree",
    ),
    ContentType.MOTIVATIONAL: (
        "تقدر",
        "استمر",
        "نجاح",
        "متستسلمش",
        "لا تستسلم",
        "بتقدر",
        "motivation",
        "never give up",
        "keep going",
        "success",
    ),
    ContentType.TUTORIAL: (
        "خطوة",
        "طريقة",
        "اعمل",
        "سوي",
        "how",
        "tutorial",
        "step",
        "guide",
    ),
    ContentType.ANALYSIS: (
        "تحليل",
        "سبب",
        "لان",
        "نتيجة",
        "السبب",
        "analysis",
        "because",
        "reason",
        "therefore",
    ),
    ContentType.REACTION_WORTHY: (
        "مفاجأة",
        "مش معقول",
        "لا يعقل",
        "بجد",
        "wow",
        "no way",
        "unbelievable",
        "shocking",
    ),
}

FILLER_CUES: tuple[str, ...] = (
    "يعني",
    "اممم",
    "امم",
    "اه",
    "طيب",
    "المهم",
    "عموما",
    "زائد",
    "umm",
    "uh",
    "erm",
    "you know",
    "like i said",
    "anyway",
)

PAYOFF_CUES: tuple[str, ...] = (
    "في الاخر",
    "في الآخر",
    "النتيجة",
    "طلع",
    "اكتشف",
    "الحل",
    "بالتالي",
    "ended up",
    "turns out",
    "the result",
    "in the end",
    "discovered",
    "the solution",
)

STORY_BUILDUP_CUES: tuple[str, ...] = (
    "في يوم",
    "وبعدين",
    "لما",
    "كان في",
    "once",
    "then",
    "suddenly",
    "فجأة",
)

CONTRAST_CUES: tuple[str, ...] = (
    "بس",
    "لكن",
    "رغم",
    "في الحقيقة",
    "الصراحة",
    "مع ذلك",
    "but",
    "however",
    "although",
    "actually",
    "even though",
    "on the other hand",
)

NUMBER_WORDS: tuple[str, ...] = (
    "واحد",
    "اتنين",
    "تلاتة",
    "مية",
    "الف",
    "مليون",
    "two",
    "three",
    "hundred",
    "thousand",
    "million",
    "percent",
)

SEARCH_LED_CUES: tuple[str, ...] = (
    "ازاي",
    "ايه هو",
    "ايه هي",
    "امتي",
    "فين",
    "كيف",
    "ما هو",
    "ما هي",
    "ليش",
    "how to",
    "what is",
    "when did",
    "where is",
    "why does",
    "why do",
)

HOOK_DIRECTION_CUES: dict[HookType, tuple[str, ...]] = {
    HookType.CURIOSITY: (
        "مش متوقع",
        "المفاجأة",
        "مكنتش اعرف",
        "غريب",
        "عجيب",
        "you won't believe",
        "surprising",
        "the secret",
    ),
    HookType.CONTRADICTION: CONTRAST_CUES,
    HookType.QUESTION: ("؟", "?"),
    HookType.DIRECT_CLAIM: (
        "الحقيقة",
        "القاعدة",
        "السر",
        "الصراحة",
        "the truth",
        "the rule",
    ),
    HookType.EMOTIONAL: CONTENT_CUES[ContentType.EMOTIONAL],
    HookType.PAYOFF_FIRST: PAYOFF_CUES,
    HookType.CONTEXTUAL: STORY_BUILDUP_CUES,
    HookType.SEARCH_LED: SEARCH_LED_CUES,
}
